package eu.erasmuswithoutpaper.common.control;

public class EwpConstants {
    public static final String ECHO_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-echo/blob/stable-v2/manifest-entry.xsd";
    public static final String INSTITUTION_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-institutions/blob/stable-v2/manifest-entry.xsd";
    public static final String ORGANIZATION_UNIT_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-ounits/blob/stable-v2/manifest-entry.xsd";
    public static final String COURSE_REPLICATION_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-course-replication/blob/stable-v1/manifest-entry.xsd";
    public static final String COURSES_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-courses/blob/stable-v1/manifest-entry.xsd";
    public static final String IIAS_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/stable-v7/manifest-entry.xsd";
    public static final String IIAS_CNR_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-iia-cnr/blob/stable-v3/manifest-entry.xsd";
    public static final String IIAS_APPROVAL_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-iias-approval/blob/stable-v2/manifest-entry.xsd";
    public static final String IIAS_APPROVAL_CNR_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-iia-approval-cnr/blob/stable-v2/manifest-entry.xsd";
    public static final String FACTSHEET_NAMESPACE = "https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-factsheet/v1.2.0/manifest-entry.xsd";
    public static final String OUTGOING_MOBILITIES_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-omobilities/blob/v2.0.0/manifest-entry.xsd";
    public static final String OUTGOING_MOBILITIES_LAS_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/manifest-entry.xsd";
    public static final String OUTGOING_MOBILITIES_LA_CNR_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/blob/stable-v1/manifest-entry.xsd";
    public static final String OUTGOING_MOBILITIES_CNR_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-omobility-cnr/blob/stable-v1/manifest-entry.xsd";
    public static final String INCOMING_MOBILITIES_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-imobilities/blob/stable-v1/manifest-entry.xsd";
    public static final String INCOMING_MOBILITIES_CNR_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-imobility-cnr/blob/stable-v1/manifest-entry.xsd";
    public static final String INCOMING_MOBILITIES_TORS_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tors/blob/stable-v1/manifest-entry.xsd";
    public static final String INCOMING_MOBILITIES_TORS_CNR_NAMESPACE = "https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tor-cnr/blob/stable-v1/manifest-entry.xsd";
    
    public static final String ECHO_VERSION = "2.0.1";
    public static final String INSTITUTION_VERSION = "2.2.0";
    public static final String DISCOVERY_VERSION = "6.0.0";
    public static final String ORGANIZATION_UNIT_VERSION = "2.1.1";
    public static final String COURSES_VERSION = "0.7.1";
    public static final String COURSE_REPLICATION_VERSION = "1.0.0";
    public static final String OUTGOING_MOBILITIES_VERSION = "3.0.0";
    public static final String OUTGOING_MOBILITY_CNR_VERSION = "2.0.0";
    public static final String OUTGOING_MOBILITIES_STATS_VERSION = "1.0.0";
    public static final String OUTGOING_MOBILITIES_LAS_VERSION = "1.2.0";
    public static final String INCOMING_MOBILITIES_VERSION = "2.0.0";
    public static final String INCOMING_MOBILITY_CNR_VERSION = "2.0.0";
    public static final String INCOMING_MOBILITIES_TORS_VERSION = "0.7.0";
    public static final String INCOMING_MOBILITY_TORS_CNR_VERSION = "0.1.0";
    public static final String IIAS_VERSION = "7.0.0";
    public static final String IIA_CNR_VERSION = "3.0.0";
    public static final String IIAS_APPROVAL_VERSION = "2.0.0";
    public static final String IIA_APPROVAL_CNR_VERSION = "2.0.0";
    public static final String FACTSHEET_VERSION = "1.2.0";

    public static final String ECHO_CLIENT_VERSION = "2.0.1";
    public static final String INSTITUTION_CLIENT_VERSION = "2.2.0";
    public static final String DISCOVERY_CLIENT_VERSION = "6.0.0";
    public static final String ORGANIZATION_UNIT_CLIENT_VERSION = "2.1.1";
    public static final String COURSES_CLIENT_VERSION = "0.7.0";
    public static final String COURSE_REPLICATION_CLIENT_VERSION = "1.0.0";
    public static final String OUTGOING_MOBILITIES_CLIENT_VERSION = "1.0.0";
    public static final String OUTGOING_MOBILITIES_CNR_CLIENT_VERSION = "1.0.0";
    public static final String OUTGOING_MOBILITIES_LA_CNR_CLIENT_VERSION = "1.0.0";
    public static final String INCOMING_MOBILITIES_CLIENT_VERSION = "0.1.0";
    public static final String INCOMING_MOBILITY_CNR_CLIENT_VERSION = "0.1.0";
    public static final String INCOMING_MOBILITIES_TORS_CLIENT_VERSION = "0.7.0";
    public static final String INCOMING_MOBILITY_TORS_CNR_CLIENT_VERSION = "0.1.0";
    public static final String IIAS_CLIENT_VERSION = "7.0.0";
    public static final String IIA_CNR_CLIENT_VERSION = "3.0.0";
    public static final String IIAS_APPROVAL_CLIENT_VERSION = "2.0.0";
    public static final String IIAS_APPROVAL_CNR_CLIENT_VERSION = "2.0.0";
}
